In [15]:
import random
import numpy as np

In [20]:
def get_vector(size):
    return np.random.random_integers(0, 1, size)

def flip_random(v):
    idx = random.randrange(0, len(v))
    v[idx] = v[idx] == 0

In [21]:
v = get_vector(10)
print(v)
for _ in range(5):
    flip_random(v)
    print(v)

[0 0 0 1 1 1 1 1 1 0]
[0 1 0 1 1 1 1 1 1 0]
[0 1 0 1 1 1 1 0 1 0]
[1 1 0 1 1 1 1 0 1 0]
[1 1 0 1 1 1 1 0 1 1]
[1 1 0 1 1 1 1 0 1 0]


/Users/Uduse/.local/share/virtualenvs/rl_notebooks-p-VYNRkp/lib/python3.6/site-packages/ipykernel_launcher.py:2: DeprecationWarning: This function is deprecated. Please call randint(0, 1 + 1) instead
  


In [35]:
result = {}
num_samples = 800
for size in range(2, 20):
    for cut_off in (50, 100, 500):
        samples = []
        for _ in range(num_samples):
            flag = False
            start = get_vector(size)
            goal = get_vector(size)
            for step in range(cut_off):
                if (start == goal).all():
                    flag = True
                    break
                flip_random(start)
            samples.append(flag)
        result[(size, cut_off)] = (np.mean(samples), np.sum(samples))

/Users/Uduse/.local/share/virtualenvs/rl_notebooks-p-VYNRkp/lib/python3.6/site-packages/ipykernel_launcher.py:2: DeprecationWarning: This function is deprecated. Please call randint(0, 1 + 1) instead
  


In [36]:
for key, val in result.items():
    print(key, val)

(2, 50) (1.0, 800)
(2, 100) (1.0, 800)
(2, 500) (1.0, 800)
(3, 50) (0.99875, 799)
(3, 100) (1.0, 800)
(3, 500) (1.0, 800)
(4, 50) (0.90875, 727)
(4, 100) (0.995, 796)
(4, 500) (1.0, 800)
(5, 50) (0.7325, 586)
(5, 100) (0.92125, 737)
(5, 500) (1.0, 800)
(6, 50) (0.4775, 382)
(6, 100) (0.74125, 593)
(6, 500) (0.99625, 797)
(7, 50) (0.29375, 235)
(7, 100) (0.48375, 387)
(7, 500) (0.95, 760)
(8, 50) (0.15875, 127)
(8, 100) (0.26875, 215)
(8, 500) (0.80125, 641)
(9, 50) (0.1, 80)
(9, 100) (0.13125, 105)
(9, 500) (0.59375, 475)
(10, 50) (0.03875, 31)
(10, 100) (0.0825, 66)
(10, 500) (0.34, 272)
(11, 50) (0.02875, 23)
(11, 100) (0.0375, 30)
(11, 500) (0.15625, 125)
(12, 50) (0.01, 8)
(12, 100) (0.02375, 19)
(12, 500) (0.10375, 83)
(13, 50) (0.01, 8)
(13, 100) (0.01375, 11)
(13, 500) (0.05375, 43)
(14, 50) (0.00375, 3)
(14, 100) (0.0075, 6)
(14, 500) (0.03, 24)
(15, 50) (0.00125, 1)
(15, 100) (0.00125, 1)
(15, 500) (0.01375, 11)
(16, 50) (0.00125, 1)
(16, 100) (0.0025, 2)
(16, 500) (0.00875, 7